import type { ModelDefinition, TaskType } from './types';

export const MODEL_CATALOG: ModelDefinition[] = [
	{
		provider: 'openai',
		model: 'gpt-4o-mini',
		qualityTier: 'medium',
		costTier: 1,
		latencyTier: 1,
		contextWindow: 128000,
		jsonReliability: 0.93,
		inputUsdPer1M: 0.15,
		outputUsdPer1M: 0.6,
	},
	{
		provider: 'openai',
		model: 'gpt-4.1-mini',
		qualityTier: 'high',
		costTier: 2,
		latencyTier: 2,
		contextWindow: 128000,
		jsonReliability: 0.96,
		inputUsdPer1M: 0.4,
		outputUsdPer1M: 1.6,
	},
	{
		provider: 'openai',
		model: 'gpt-4.1',
		qualityTier: 'high',
		costTier: 3,
		latencyTier: 3,
		contextWindow: 128000,
		jsonReliability: 0.97,
		inputUsdPer1M: 2.0,
		outputUsdPer1M: 8.0,
	},
	{
		provider: 'anthropic',
		model: 'claude-3-5-haiku-latest',
		qualityTier: 'medium',
		costTier: 1,
		latencyTier: 1,
		contextWindow: 200000,
		jsonReliability: 0.9,
		inputUsdPer1M: 0.8,
		outputUsdPer1M: 4.0,
	},
	{
		provider: 'anthropic',
		model: 'claude-3-5-sonnet-latest',
		qualityTier: 'high',
		costTier: 2,
		latencyTier: 2,
		contextWindow: 200000,
		jsonReliability: 0.95,
		inputUsdPer1M: 3.0,
		outputUsdPer1M: 15.0,
	},
	{
		provider: 'anthropic',
		model: 'claude-3-7-sonnet-latest',
		qualityTier: 'high',
		costTier: 3,
		latencyTier: 3,
		contextWindow: 200000,
		jsonReliability: 0.96,
		inputUsdPer1M: 3.0,
		outputUsdPer1M: 15.0,
	},
	{
		provider: 'gemini',
		model: 'gemini-1.5-flash',
		qualityTier: 'low',
		costTier: 1,
		latencyTier: 1,
		contextWindow: 1000000,
		jsonReliability: 0.84,
		inputUsdPer1M: 0.075,
		outputUsdPer1M: 0.3,
	},
	{
		provider: 'gemini',
		model: 'gemini-1.5-pro',
		qualityTier: 'high',
		costTier: 2,
		latencyTier: 2,
		contextWindow: 2000000,
		jsonReliability: 0.9,
		inputUsdPer1M: 1.25,
		outputUsdPer1M: 5.0,
	},
];

export const TASK_DEFAULTS: Record<TaskType, Array<{ provider: ModelDefinition['provider']; model: string }>> = {
	classification: [
		{ provider: 'gemini', model: 'gemini-1.5-flash' },
		{ provider: 'openai', model: 'gpt-4o-mini' },
		{ provider: 'anthropic', model: 'claude-3-5-haiku-latest' },
	],
	summarization: [
		{ provider: 'gemini', model: 'gemini-1.5-flash' },
		{ provider: 'openai', model: 'gpt-4o-mini' },
		{ provider: 'anthropic', model: 'claude-3-5-haiku-latest' },
	],
	extraction: [
		{ provider: 'openai', model: 'gpt-4.1-mini' },
		{ provider: 'anthropic', model: 'claude-3-5-sonnet-latest' },
		{ provider: 'gemini', model: 'gemini-1.5-pro' },
	],
	coding: [
		{ provider: 'anthropic', model: 'claude-3-7-sonnet-latest' },
		{ provider: 'openai', model: 'gpt-4.1' },
		{ provider: 'gemini', model: 'gemini-1.5-pro' },
	],
	reasoning: [
		{ provider: 'anthropic', model: 'claude-3-7-sonnet-latest' },
		{ provider: 'openai', model: 'gpt-4.1' },
		{ provider: 'gemini', model: 'gemini-1.5-pro' },
	],
	creative: [
		{ provider: 'anthropic', model: 'claude-3-5-sonnet-latest' },
		{ provider: 'openai', model: 'gpt-4.1' },
		{ provider: 'gemini', model: 'gemini-1.5-pro' },
	],
	'safety-sensitive': [
		{ provider: 'openai', model: 'gpt-4.1' },
		{ provider: 'anthropic', model: 'claude-3-7-sonnet-latest' },
		{ provider: 'gemini', model: 'gemini-1.5-pro' },
	],
};
